/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.model.view;

import UpperEssential.UpperEssentialLookAndFeel;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author homer
 */
public class mainView extends javax.swing.JFrame {

    private JDesktopPane jdpDesktop;
    private static int openFrameCount = 0;
    private BufferedImage img;
    GestionFactura gestionFactura = null;
    GestionTarget gestionTarget = null;
    GestionPublicidad gestionPublicidad = null;
    GestionUsuarios gestionUsuarios = null;
    GestionEmpresas gestionEmpresas = null;
    GestionCampania gestionCampania = null;

    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("HitchUs - Administración de Publicidad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        escritorio = new javax.swing.JDesktopPane() {
            private Image image;

            {
                try {
                    image = ImageIO.read(getClass().getResourceAsStream(
                        "/ec/edu/espe/images/Titulo.png"));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(image, getWidth()/4, getHeight()/4, getWidth()/2, getHeight()/2, this);
        }
    };
    escritorio.setBackground(new java.awt.Color(204, 255, 255));
    escritorio.setAutoscrolls(true);

    javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
    escritorio.setLayout(escritorioLayout);
    escritorioLayout.setHorizontalGroup(
        escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 843, Short.MAX_VALUE)
    );
    escritorioLayout.setVerticalGroup(
        escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 481, Short.MAX_VALUE)
    );

    jMenuBar1.setBackground(new java.awt.Color(64, 159, 129));

    jMenu1.setText("Usuarios");
    jMenu1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenu1ActionPerformed(evt);
        }
    });

    jMenuItem1.setText("Gestionar");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem1ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem1);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Empresas");

    jMenuItem2.setText("Registros");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItem2);

    jMenuItem6.setText("Facturas");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem6ActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItem6);

    jMenuItem7.setText("Detalles por Factura");
    jMenu2.add(jMenuItem7);

    jMenuBar1.add(jMenu2);

    jMenu4.setText("Campañas");

    jMenuItem4.setText("Campaña");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
        }
    });
    jMenu4.add(jMenuItem4);

    jMenuItem9.setText("Estadísticas");
    jMenu4.add(jMenuItem9);

    jMenuItem10.setText("Historial");
    jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem10ActionPerformed(evt);
        }
    });
    jMenu4.add(jMenuItem10);

    jMenuBar1.add(jMenu4);

    jMenu3.setText("Publicidad");

    jMenuItem3.setText("Elementos");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    jMenu3.add(jMenuItem3);

    jMenuBar1.add(jMenu3);

    jMenu5.setText("Target");

    jMenuItem5.setText("Target Edad");
    jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem5ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem5);

    jMenuItem11.setText("Segmentación ");
    jMenu5.add(jMenuItem11);

    jMenuBar1.add(jMenu5);

    jMenu6.setText("Configuración");
    jMenu6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenu6ActionPerformed(evt);
        }
    });

    jMenuItem8.setText("Cerrar Sesión");
    jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem8ActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItem8);

    jMenuBar1.add(jMenu6);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(escritorio)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (gestionUsuarios != null) {
            if (gestionUsuarios.isShowing()) {
                JOptionPane.showMessageDialog(null, "Cierre la ventana antes de abrir una nueva");
            } else {
                gestionUsuarios = new GestionUsuarios();
                this.escritorio.add(gestionUsuarios);
                gestionUsuarios.show();
                gestionUsuarios.setResizable(true);
                gestionUsuarios.setClosable(true);
            }
        } else {
            gestionUsuarios = new GestionUsuarios();
            this.escritorio.add(gestionUsuarios);
            gestionUsuarios.show();
            gestionUsuarios.setResizable(true);
            gestionUsuarios.setClosable(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (gestionEmpresas != null) {
            if (gestionEmpresas.isShowing()) {
                JOptionPane.showMessageDialog(null, "Cierre la ventana antes de abrir una nueva");
            } else {
                gestionEmpresas = new GestionEmpresas();
                this.escritorio.add(gestionEmpresas);
                gestionEmpresas.show();
                gestionEmpresas.setResizable(true);
                gestionEmpresas.setClosable(true);
            }
        } else {
            gestionEmpresas = new GestionEmpresas();
            this.escritorio.add(gestionEmpresas);
            gestionEmpresas.show();
            gestionEmpresas.setResizable(true);
            gestionEmpresas.setClosable(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (gestionCampania != null) {
            if (gestionCampania.isShowing()) {
                JOptionPane.showMessageDialog(null, "Cierre la ventana antes de abrir una nueva");
            } else {
                gestionCampania = new GestionCampania();
                this.escritorio.add(gestionCampania);
                gestionCampania.show();
                gestionCampania.setResizable(true);
                gestionCampania.setClosable(true);
            }
        } else {
            gestionCampania = new GestionCampania();
            this.escritorio.add(gestionCampania);
            gestionCampania.show();
            gestionCampania.setResizable(true);
            gestionCampania.setClosable(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (gestionPublicidad != null) {
            if (gestionPublicidad.isShowing()) {
                JOptionPane.showMessageDialog(null, "Cierre la ventana antes de abrir una nueva");
            } else {
                gestionPublicidad = new GestionPublicidad();
                this.escritorio.add(gestionPublicidad);
                gestionPublicidad.show();
                gestionPublicidad.setResizable(true);
                gestionPublicidad.setClosable(true);
            }
        } else {
            gestionPublicidad = new GestionPublicidad();
            this.escritorio.add(gestionPublicidad);
            gestionPublicidad.show();
            gestionPublicidad.setResizable(true);
            gestionPublicidad.setClosable(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (gestionTarget != null) {
            if (gestionTarget.isShowing()) {
                JOptionPane.showMessageDialog(null, "Cierre la ventana antes de abrir una nueva");
            } else {
                gestionTarget = new GestionTarget();
                this.escritorio.add(gestionTarget);
                gestionTarget.show();
                gestionTarget.setResizable(true);
                gestionTarget.setClosable(true);
            }
        } else {
            gestionTarget = new GestionTarget();
            this.escritorio.add(gestionTarget);
            gestionTarget.show();
            gestionTarget.setResizable(true);
            gestionTarget.setClosable(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        if (gestionFactura != null) {
            if (gestionFactura.isShowing()) {
                JOptionPane.showMessageDialog(null, "Cierre la ventana antes de abrir una nueva");
            } else {
                gestionFactura = new GestionFactura();
                this.escritorio.add(gestionFactura);
                gestionFactura.show();
                gestionFactura.setResizable(true);
                gestionFactura.setClosable(true);
            }
        } else {
            gestionFactura = new GestionFactura();
            this.escritorio.add(gestionFactura);
            gestionFactura.show();
            gestionFactura.setResizable(true);
            gestionFactura.setClosable(true);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());

            Login l = new Login();
            l.setLocationRelativeTo(null);
            l.setVisible(true);
            dispose();
        } catch (UnsupportedLookAndFeelException ex) {
            System.out.println("Impossible load theme.");
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(getClass().getResource(
                        "/ec/edu/espe/images/HitchLogo.png"));
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
